# Generated by Django 2.2.4 on 2019-08-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goederen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goederennotitie',
            old_name='inhoud',
            new_name='notitie',
        ),
    ]
